### ISSUE TITLE
Support Navigate with arguments in none Android target

### ISSUE THREAD

**Issue by Darkrai9x** [MatkovIvan/nav_cupcake#4]
I have tried navigation on Android, it works well, but on desktop and iOS, navigation with parameters doesn't seem to work.

`composable(route = "flavor/{id}") { }`

`navController.navigate("flavor/test")`

It seems this issue is related to deep links not fully supported by NavController.jb yet. Could you please provide information about when this feature will be supported?

**Comment by MatkovIvan** [comment]
Thanks for the report. Yes, it's because deep-link matching is not ported to multiplatform yet. There is no particular ETA, but it's in my TODO list.
