### ISSUE TITLE
Did you mean to go from 2.8.0 to 2.7.0 of navigation-compose?

### ISSUE THREAD

**Issue by ColtonIdle** [MatkovIvan/nav_cupcake#6]
See here: https://github.com/MatkovIvan/nav_cupcake/commit/1ea09053c51fbcf2aaba628e5c2173dbc2c25747

You went from 2.8 to 2.7. I think maybe that's a mistake.

![CleanShot 2024-05-22 at 00 42 04@2x](https://github.com/MatkovIvan/nav_cupcake/assets/31751141/11ad535c-be4c-4e70-8727-b7fd6a7312bd)

**Comment by MatkovIvan** [comment]
No, it was a valid change. The reason that we temporarily rebased navigation to 2.7 branch is that 2.8 is not compatible with Compose 1.6 on Android (we're using original Google artifacts there).

The related change in the library: https://github.com/JetBrains/compose-multiplatform-core/pull/1315
The issue that it solves: https://github.com/JetBrains/compose-multiplatform/issues/4677 (basically you cannot use any experimental API that were changed between Compose 1.6 and 1.7)

We'll ship a version based on 2.8 together with Compose 1.7
